/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fcZsgXM5q4u
 */
import { Button } from '@/components/ui/button'
import { CardContent, Card } from '@/components/ui/card'
import { DiagonalArrow } from './Icons'

export function NewCard() {
  return (
    <section className=" bg-gray-900 dark:bg-gray-100 flex items-center justify-center">
      <Card className="bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-100">
        <CardContent className="space-y-4">
          <p className="text-lg">
            Welcome to our platform! Click the button below to get started.
          </p>
          <Button
            className="text-gray-900 dark:text-gray-100 bg-gray-100 dark:bg-gray-800 underline"
            variant="ghost">
            <span>Start Now</span>
            <DiagonalArrow />
          </Button>
        </CardContent>
      </Card>
    </section>
  )
}
